### ISSUE TITLE
pickle file './le.pickle'

### ISSUE THREAD

**Issue by pouryajafarzadeh** [imironica/liveness#2]
Hello
In test_livenessNet.py the line:

le = pickle.loads(open(label_encoder, "rb").read())

will load 

label_encoder = './le.pickle'

but there is no file 'le.pickle' in the folder.
the code has error in finding the file.

**Comment by zanfirandra** [comment]
Hello
Thanks for reporting this 😄 I think this file should be generated by `LabelEncoder` in the `train_livenessNet.py`. 
I'll come back with a fix soon as possible

**Comment by zanfirandra** [comment]
Actually pickle file is not valid anymore :flushed: . ` test_livenessNet.py` it's now updated it [here](https://github.com/imironica/liveness/commit/d1fa723d78f6ee5f4496c3b9f85b4e413d9505eb) and actually it's same thing as for the mobile net in `5_transfer_learning` . 

  `train_livenessNet.py` also validates the model and computes Confusion Matrix and Classification Report. I also retrained the model, you can see the results in [readme](https://github.com/imironica/liveness/commit/76126f4f0a62d7b11e5c7bc8195ac733255b4b5c)

Note: I updated the packages `tensorflow version 2.2.0` `keras version 2.4.3` and the api at [this commit](https://github.com/imironica/liveness/commit/beedab8c7ee64e864a07e977e63248699a4d525a) 

I tested it and now it works.

It's ok now? 😄 @pouryajafarzadeh
