### ISSUE TITLE
test_livenessNet.py  always shows 'Fake'

### ISSUE THREAD

**Issue by naushadck** [imironica/liveness#3]
test_livenessNet.py  always shows "Fakes"  for real face.

**Comment by zanfirandra** [comment]
Hello :) Did you use the pretrained model or you trained the model with your set of data?

**Comment by naushadck** [comment]
Hello, 

I used my image that is to verify as real or fake.... 
"liveness_model.h5" pre-trained model is used. 

     On Thursday, August 27, 2020, 10:43:51 AM GMT+4, zanfirandra <notifications@github.com> wrote:  
 
 


Hello :) Did you use the pretrained model or you trained the model with your set of data?

**Comment by naushadck** [comment]
"liveness_model.h5" pre-trained model is used.

**Comment by zanfirandra** [comment]
Ok, i'll look into it as soon as possible. Until then, If you want you can try to checkout this commit [d1fa723d78f6ee5f4496c3b9f85b4e413d9505eb](https://github.com/imironica/liveness/commit/d1fa723d78f6ee5f4496c3b9f85b4e413d9505eb) which is before I retrained the model and let me know how it goes.
