### ISSUE TITLE
how predict if my face is liveness or it's just a video of me?

### ISSUE THREAD

**Issue by baharjalali** [imironica/liveness#5]
hi
should i create a folder 'dataset' with two sub folder 'real' and 'fake' and import some image as real and fake of my face into them?
so why we use train and test images? 
it's better program can detect fake and real faces without any new data. it should just predict new data.

**Comment by ghost** [comment]
@baharjalali I don't know if you've fixed your problem or not, but the datasets is available within the repository, in the folder called db. You have to run all the files sequentially to preprocess and then train the model.
